### ISSUE TITLE
[bug report] Rename folder failed.

### ISSUE THREAD

**Issue by Andy-AO** [pjeby/quick-explorer#28] opened 2021-12-21 00:00 UTC
The folder itself can be renamed, but links can't.

![image](https://user-images.githubusercontent.com/38101170/146848309-4dd8aadc-08da-496a-852a-a62d6246caf8.png)

**Comment by pjeby** [comment] 2021-12-21 01:09
This isn't enough information to reduce the problem.  I am able to rename folders just fine on my Obsidian, with links being updated.  Please provide step-by-step instructions for reproducing the issue.

**Comment by Andy-AO** [comment] 2021-12-21 01:13
> This isn't enough information to reproduce the problem. I am able to rename folders just fine on my Obsidian, with links being updated. Please provide step-by-step instructions for reproducing the issue.

I'll try

**Comment by pjeby** [comment] 2022-01-18 08:30
Closing since no information was provided for reproducing the issue.  Feel free to open another if you are able to provide instructions to reproduce.

**Closed by pjeby** 2022-01-18 08:30 UTC

**Comment by Andy-AO** [comment] 2022-01-21 01:35
> Closing since no information was provided for reproducing the issue. Feel free to open another if you are able to provide instructions to reproduce.

 I have reproduced it now.  Please click [[bug report] Rename folder failed. · Issue #4 · pjeby/note-folder-autorename](https://github.com/pjeby/note-folder-autorename/issues/4).
