### ISSUE TITLE
Breadcrumbs broken in California Coast

### ISSUE THREAD

**Issue by jacklaing** [pjeby/quick-explorer#3] opened 2021-09-02 20:51 UTC
I wasn't sure whether to post this issue on the California Coast repo or this one. I settled on this one because I figured you're more likely to know what's going wrong and I can relay the solution if need be.

The breadcrumbs in California stack vertically in California Coast for some reason, rather than horizontally, which breaks the navigation UX.

![quick-explorer-california-coast](https://user-images.githubusercontent.com/43007530/131914361-39b6b6ec-338e-4118-8fda-cef9d9e9d821.gif)

**Comment by pjeby** [comment] 2021-09-02 21:54
So, the issue is that California Coast changes the titlebar layout to be flex-based, but quick-explorer uses inline block.  I would change it to flex (which works), but then *other* themes break that aren't flex-based.   So this is going to have to be fixed in California Coast, or any other theme that changes the title bar layout.  :disappointed:

**Comment by pjeby** [comment] 2021-09-02 21:55
Oh, forgot to mention: the specific fix is to set `#quick-explorer { display: flex }`.  You can do that in a CSS snippet until there's a fix for the theme, or if somebody can come up with a `display` I can use for QE that works across all themes.

**Comment by pjeby** [comment] 2021-09-02 22:00
Also, it seems to work just as well for California Coast to just *not* use `display: flex` for the titlebar items, so that's an option too.  As far as I can tell, getting rid of the `display` on the titlebar-related items makes QE work fine and doesn't break anything that I can tell.

**Comment by jacklaing** [comment] 2021-09-02 22:06
Hey @pjeby, just saw your messages after finding a solution in Discord https://ptb.discord.com/channels/686053708261228577/702656734631821413/883097557197262929

It is indeed as you say.

I'm going to use the following CSS in the snippet layer to correct it until/if California Coast fixes it.

To correct the layout:
```
.explorable.titlebar-button { display: unset}

#quick-explorer { background-color: var(--background-translucent) !important}
```

To force visibility:
```
.titlebar-button-container.mod-left {
    opacity: 1;
    transition: opacity 100ms ease-out;
}
```

**Closed** 2021-09-02 22:38 UTC

**Comment by pjeby** [comment] 2021-09-02 22:41
The first two fixes are now in the code base, so only the opacity thing should be needed now, as a specific California Coast thing.

**Comment by pjeby** [comment] 2021-09-02 22:42
Oh, and thank you for both reporting the issue and sharing the tweaks!
