### ISSUE TITLE
Start problem 0.15.8 

### ISSUE THREAD

**Issue by ClusterWood** [pjeby/quick-explorer#46] opened 2022-07-25 09:22 UTC
quick-explorer .34 still not starting with Obsidian 0.15.8

regards,
ClusterWood

**Comment by pjeby** [comment] 2022-07-25 09:55
What do you mean by "not starting"?  It's working for me on 0.15.8, so could you be more specific?

**Comment by ClusterWood** [comment] 2022-07-25 10:08
![qe_error](https://user-images.githubusercontent.com/104789621/180752356-90178064-f8df-4d11-9a7a-f91c96e91567.jpg)

This error happens since .33 
V.32  is working well.

**Comment by pjeby** [comment] 2022-07-25 20:10
Ok, what is your "installer version" (shown in the About section of Obsidian settings; it is *not* the same thing as the Obsidian version, but appears underneath with the words "installer version:" in parentheses)?

Also, what errors are shown in the dev console?  (ctrl or cmd-shift-I to open it, errors are shown in pink and red near the bottom)

**Comment by ClusterWood** [comment] 2022-07-25 21:20
The "installer version" shown is 0.15.8

Plugin failure: quick-explorer TypeError: Cannot read properties of null (reading 'cloneNode')
    at I.onload (plugin:quick-explorer:1:27671)
    at I.e.load (app.js:1:731189)
    at Y.e.load (app.js:1:731248)
    at B.e.load (app.js:1:731248)
    at q.e.load (app.js:1:731248)
    at e.<anonymous> (app.js:1:1547814)
    at app.js:1:235078
    at Object.next (app.js:1:235183)
    at s (app.js:1:233922)
(anonymous) @ app.js:1

I hope this helps.

**Comment by pjeby** [comment] 2022-07-25 21:26
Do you have any plugins that remove the Obsidian title text?  (The bit that usually says "Note Name - Vault Name - Obsidian 0.15.8".)  The error shown indicates that Quick Explorer isn't finding it in a window's title bar.

**Comment by ClusterWood** [comment] 2022-07-25 21:37
Yes, that's it:
Customizable Page Header and Title Bar Obsidian Plugin
obsidian://show-plugin?id=customizable-page-header-buttons

If I disable this plugin version .34 is working as expected. But this side effect only occurs with the new version.
Can you fix it?
Regards,
ClusterWood

**Comment by pjeby** [comment] 2022-07-25 22:36
Yes, it should be fixed in 0.1.35.  The issue is that QE wants to move the title to the side out of its way, but the CPHATB plugin has already removed the title if you are using center buttons.  So QE will now check to see if the title is there before trying to move it.

**Closed by pjeby** 2022-07-25 22:36 UTC
