### ISSUE TITLE
[Bug] Middle-click on a note causes cursor to switch icon to scroll and doesn't reset

### ISSUE THREAD

**Issue by j-maffe** [pjeby/quick-explorer#79] opened 2023-05-31 21:17 UTC
It would be a nice feature if middle-clicking a note would act the same as ctrl+click. But besides that, currently just middle-clicking anywhere in the quick-explorer menu just causes the cursor to switch to the 4-arrow icon indicating middle-click scroll that you see when you middle-click empty space. I haven't found any way to fix it except to restart Obsidian. It's nothing too catastrophic, but you'd be surprised how many times I have to restart Obsidian per day just due to this😅

**Comment by pjeby** [comment] 2023-06-01 00:00
Interesting - I don't seem to be able to duplicate that.  Does it happen when you middle-click any other links in Obsidian?

**Comment by j-maffe** [comment] 2023-06-01 08:03
No, I only see this behavior with the address bar with Quick Explorer. I did some plugin bug-hunting and narrowed it down to the [Obsidian Table Enhancer Plugin](https://github.com/Stardusten/ob-table-enhancer). It may be an alteration to mouse click behavior that's clashing with your plugin. I have no idea how that can be fixed but I'll report it there as well as they might figure out what it is. Thanks for checking!

**Comment by pjeby** [comment] 2023-06-01 11:59
That plugin does indeed appear to install global mousedown and click handlers that are asynchronous and yet manipulate event propagation and defaults; I'm not sure if that's the source of the problem, but it's certainly what I'd check first.

I'm going to go ahead and close this since you've confirmed the bug only happens with that plugin enabled.

**Closed by pjeby** 2023-06-01 11:59 UTC
