### ISSUE TITLE
[Bug Report] Doesn't close or open notes

### ISSUE THREAD

**Issue by selfire1** [pjeby/quick-explorer#35] opened 2022-03-16 07:42 UTC
Hi! I am on mac, Obsidian `v0.14.0`. After opening Quick Explorer by clicking on it in the title bar, I can't close it.

Here is the error form from the console.
<img width="193" alt="Screenshot 2022-03-16 at 13 25 15" src="https://user-images.githubusercontent.com/70809675/158540457-82a42830-baf6-4505-b1b3-32a2f9525573.png">

**Comment by pjeby** [comment] 2022-03-16 08:07
What version of Hover Editor are you using?

**Comment by pjeby** [comment] 2022-03-16 08:11
Never mind - I see the problem is when you're *not* using Hover Editor.  I should have a fix shortly.

**Comment by pjeby** [comment] 2022-03-16 08:22
Should be fixed in 0.1.17.

**Closed** 2022-03-16 08:22 UTC
